spring.application.name=booking-service
server.port=8081

# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5435/booking_db
spring.datasource.username=app
spring.datasource.password=app

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
app.security.permit-all[0]=/public/guests
app.security.permit-all[1]=/api/reservations/quote
app.security.permit-all[2]=/api/reservations/reserved-ids
app.security.permit-all[3]=/api/reservations/rooms/*/has-future
app.security.permit-all[4]=/error
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.flyway.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8