services:
  db-identity:
    image: postgres:16
    container_name: db-identity
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"
    volumes:
      - identity_data:/var/lib/postgresql/data

  db-catalog:
    image: postgres:16
    container_name: db-catalog
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5434:5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data

  db-booking:
    image: postgres:16
    container_name: db-booking
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5435:5432"
    volumes:
      - booking_data:/var/lib/postgresql/data

  db-operations:
    image: postgres:16
    container_name: db-operations
    environment:
      POSTGRES_DB: operations_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5436:5432"
    volumes:
      - operations_data:/var/lib/postgresql/data


  # ---------- Microservices ----------
  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: booking-service
    container_name: booking-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-booking:5432/booking_db
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      APP_JWT_SECRET_BASE64: "Lqpzyu+lci2h7exyvytGnnnxErqFI7SDxtux2yPC1Gk="
      APP_JWT_EXPIRATION_MS: "3600000"
      APP_SECURITY_PERMIT_ALL_0: "/actuator/**"
      APP_SECURITY_PERMIT_ALL_1: "/public/**"
    depends_on:
      - db-booking

  catalog-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: catalog-service
    container_name: catalog-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-catalog:5432/catalog_db
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      APP_JWT_SECRET_BASE64: "Lqpzyu+lci2h7exyvytGnnnxErqFI7SDxtux2yPC1Gk="
      APP_JWT_EXPIRATION_MS: "3600000"
      APP_SECURITY_PERMIT_ALL_0: "/actuator/**"
      APP_SECURITY_PERMIT_ALL_1: "/rooms/**"
      APP_SECURITY_PERMIT_ALL_2: "/offers/**"
    depends_on:
      - db-catalog

  identity-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: identity-service
    container_name: identity-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-identity:5432/identity_db
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      APP_JWT_SECRET_BASE64: "Lqpzyu+lci2h7exyvytGnnnxErqFI7SDxtux2yPC1Gk="
      APP_JWT_EXPIRATION_MS: "3600000"
      APP_SECURITY_PERMIT_ALL_0: "/auth/**"
      APP_SECURITY_PERMIT_ALL_1: "/actuator/**"
      APP_OPERATIONS_URL: "http://operations-service:8084"
      APP_BOOKING_URL: "http://booking-service:8081"


    depends_on:
      - db-identity

  operations-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: operations-service
    container_name: operations-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-operations:5432/operations_db
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      APP_JWT_SECRET_BASE64: "Lqpzyu+lci2h7exyvytGnnnxErqFI7SDxtux2yPC1Gk="
      APP_JWT_EXPIRATION_MS: "3600000"
      APP_SECURITY_PERMIT_ALL_0: "/actuator/**"
      APP_SECURITY_PERMIT_ALL_1: "/employees/**"
    depends_on:
      - db-operations

  # ---------- Gateway ----------
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - booking-service
      - catalog-service
      - identity-service
      - operations-service

volumes:
  identity_data:
  catalog_data:
  booking_data:
  operations_data:
