spring.application.name=operations-service
server.port=8084

# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5436/operations_db
spring.datasource.username=app
spring.datasource.password=app

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
app.security.permit-all[0]=/employees/*
app.security.permit-all[1]=/error
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.flyway.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8
app.services.identity.base-url=http://identity-service:8083
