server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      # Route'y - czyli mapowanie ścieżek na konkretne mikroserwisy
      routes:
        - id: booking-service
          uri: http://booking-service:8081
          predicates:
            - Path=/booking/**
          filters:
            - StripPrefix=1

        - id: catalog-service
          uri: http://catalog-service:8082
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1

        - id: identity-service
          uri: http://identity-service:8083
          predicates:
            - Path=/identity/**
          filters:
            - StripPrefix=1

        - id: operations-service
          uri: http://operations-service:8084
          predicates:
            - Path=/operations/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never
